title: Drica Zenck
description: >-
  Testing github pages
baseurl: ""
url: "https://dricazenck.github.io/"

# timezone: US/Eastern

theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# github:
#   is_project_page: true

# google_analytics: UA-XX

markdown: kramdown