# Build settings
remote_theme: pages-themes/midnight@v0.2.0

# Settings
title: Women Who Code London
description: "Mentoring Program"

# GitHub
github:
  repository_url: https://dricazenck.github.io/wwcodetest.github.io/