plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: _sass/

# Settings
title: "Women Who Code London"
subtitle: "Mentoring Program"
description: "Mentoring Program v4"
author: Adriana Zenck Zimmermann

# GitHub
github:
  repository_url: https://dricazenck.github.io/wwcodetest.github.io/